{
 "title": "NOIA Nodes",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "tag", "query": "instance, alias" }
  ]
 },
 "panels": [
  {
   "title": "novy1.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"novy1.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "novy1.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"novy1.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "novy2.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"novy2.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "novy2.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"novy2.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "novy3.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"novy3.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "novy3.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"novy3.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "novy4.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"novy4.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "novy4.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"novy4.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "novy5.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"novy5.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "novy5.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"novy5.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "novy6.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"novy6.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "novy6.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"novy6.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "novy7.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"novy7.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "novy7.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"novy7.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "novy8.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"novy8.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "novy8.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"novy8.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "novy9.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"novy9.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "novy9.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 3 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"novy9.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "smart1.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"smart1.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "smart1.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 3 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"smart1.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "smart14.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 3 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"smart14.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "smart14.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 3 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"smart14.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "smart15.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"smart15.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "smart15.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"smart15.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "smart16.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"smart16.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "smart16.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"smart16.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "smart17.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"smart17.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "smart17.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"smart17.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "smart18.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"smart18.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "smart18.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 6 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"smart18.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "smart19.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"smart19.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "smart19.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 6 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"smart19.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "smart2.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"smart2.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "smart2.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"smart2.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "smart20.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 6 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"smart20.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "smart20.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"smart20.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "smart3.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"smart3.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "smart3.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"smart3.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "smart4.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"smart4.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "smart4.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"smart4.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "smart5.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"smart5.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "smart5.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"smart5.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "smart6.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"smart6.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "smart6.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"smart6.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "smart7.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"smart7.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "smart7.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"smart7.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "smart8.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 9 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"smart8.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "smart8.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"smart8.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "smart9.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"smart9.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "smart9.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 12 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"smart9.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "zaal1.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 12 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"zaal1.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "zaal1.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"zaal1.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "zaal2.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"zaal2.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "zaal2.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 12 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"zaal2.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "zaal3.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"zaal3.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "zaal3.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 12 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"zaal3.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "zaal4.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"zaal4.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "zaal4.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"zaal4.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "zaal5.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 12 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"zaal5.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "zaal5.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 12 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"zaal5.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "zaal6.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"zaal6.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "zaal6.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 15 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"zaal6.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "zaal7.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 15 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"zaal7.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "zaal7.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"zaal7.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "zaal8.noia.novy.pw uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"zaal8.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "zaal8.noia.novy.pw network",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 15 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"zaal8.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  }
 ]
}