---

- name: "set the weekly timestamp"
  cron:
    minute: "0"
    hour: "15"
    weekday: "MON"
    job: "/root/noia_weekly_uptime.sh > /root/monday_utc_timestamp.log"

- name: "set 10 minutes metrics"
  cron:
    minute: "*/10"
    job: "/bin/echo noia_uptime $(/root/noia_uptime.sh) > /var/lib/node_exporter/textfile_collector/noia_uptime.prom"

