---
# tasks file for uptime-monitor

- name: Include a prometheus node_exporter
  include: node_exporter.yml

- name: Copy necessary files
  include: copy.yml

- name: Include a cronjob creation for getting the uptime metric 
  include: cronjob.yml


