{
 "title": "NOIA Nodes",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "tag", "query": "instance, alias" }
  ]
 },
 "panels": [
  {
   "title": "novy1 uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"novy1.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "novy3 uptime",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "noia_uptime{$tag=\"novy3.noia.novy.pw\"}"
    }
   ]
  },
  {
   "title": "novy1 network",
   "type": "graph",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"novy1.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "novy3 network",
   "type": "graph",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"novy3.noia.novy.pw\", device!=\"lo\"}[5m])"
    }
   ]
  }
 ]
}