---
#- hosts: test-node
#  environment:
#    NOIA_NODE_BLOCKCHAIN_AIRDROP_ADDRESS: "{{ wallet }}"
#  roles:
#    - uptime-monitor

#- name: a play that runs entirely on the ansible host
#  hosts: 127.0.0.1
#  connection: local
#  tasks:
    #- debug: msg="{{item}}"
    #  with_lines: cat hosts.yml | grep -v "^$" | grep -v "^#" | grep -v "^\[" | awk '{print $1}'
    
#    - name: generating the uptime panel
#      shell: awk '{sub(/novy10.noia.novy.pw/,"{{item}}}")}1' uptime-panel.json > dashboards/{{item}}.json
#      with_lines: cat hosts.yml | grep -v "^$" | grep -v "^#" | grep -v "^\[" | awk '{print $1}'
      

- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local
  tasks:

    - name: generating the uptime panel
      template: src=dashboards/templates/template.json.j4 dest=dashboards/source/{{ item }}.json
      vars:
        HOSTNAME: "{{ item }}"
        ID : "{{ 9999999999 | random }}"
        ID2 : "{{ 9999999999 | random }}"
#      with_lines: cat hosts.yml | grep -v "^$" | grep -v "^#" | grep -v "^\[" | awk '{print $1}'
      with_inventory_hostnames:
        - all

    - name: collect all json files together
      assemble:
        src: dashboards/source
        dest: dashboards/final/NOIA_CACHE.json
        delimiter: ",\n"

#    - name: insertbefore
#      lineinfile:
#        path: dashboards/final/NOIA_CACHE.json
#        insertbefore: BOF
#        line: "["

    - name: insertafter
      lineinfile:
        path: dashboards/final/NOIA_CACHE.json
        insertafter: EOF
        line: "]}"