---
- name: Stop bluzelle
  systemd:
    name: blzd
    state: stopped
    enabled: yes
  tags: 
    - sentry
    - validator

- name: Remove old Genesis
  file:
    path: $HOME/.blzd/config/genesis.json
    state: absent
  tags: 
    - sentry
    - validator

- name: Reset daemon state
  shell: $HOME/go/bin/blzd unsafe-reset-all
  register: shell_result
  tags: 
    - sentry
    - validator

- debug:
    var: shell_result.stdout_lines
  tags: 
    - sentry
    - validator

- name: Insert Genesis
  get_url:
    url: http://testnet.public.bluzelle.com:1317/genesis.json
    dest: $HOME/.blzd/config/genesis.json
    mode: '0440'
  tags: 
    - sentry
    - validator

- name: Add persistent peers for sentry
  replace:
    path: $HOME/.blzd/config/config.toml
    regexp: 'persistent_peers = .*$'
    replace: 'persistent_peers = "{{ persistent_peers }}"'
  tags: sentry

- name: Add persistent peers for validator
  replace:
    path: $HOME/.blzd/config/config.toml
    regexp: 'persistent_peers = .*$'
    replace: 'persistent_peers = "{{ persistent_peers }}"'
  tags: validator

- name: Start bluzelle
  systemd:
    name: blzd
    state: started
    enabled: yes
  tags: 
    - sentry
    - validator