---
#########################################
###########MAIN#PLAYBOOK#FOR#NOIA########
#########################################

##########INITIAL INSTALLATION###########
- hosts: mihail-hosts
  environment:
    NOIA_NODE_BLOCKCHAIN_AIRDROP_ADDRESS: "{{ wallet }}"
  tasks:
    - name: Include Noia installation
      include_tasks:
        file: installation/install.yml
        apply:
          tags:
            - install
    - name: Include Noia run node
      include_tasks:
        file: installation/start.yml
        apply:
          tags:
            - run
    - include_role:
        name: uptime-monitor
  tags:
    - full-install

- hosts: mihail-hosts
  roles:
    - role: uptime-monitor
  tags:
    - metrics

- name: Include Dashboard generation
  import_playbook: monitor/dashboard.yml
  tags:
    - dashboards

- name: Include prometheus configuration
  import_playbook: monitor/prometheus_config.yml
  tags:
    - prometheus

##########SOFTWARE UPGRADE###########
- hosts: mihail-hosts
  tasks:
    - name: Include Noia installation
      include_tasks:
        file: installation/noia.yml
        apply:
          tags:
            - install
    - name: Include Noia run node
      include_tasks:
        file: installation/noia.yml
        apply:
          tags:
            - clean
    - name: Include Noia run node
      include_tasks:
        file: installation/noia.yml
        apply:
          tags:
            - update  
  tags:
    - upgrade


