#########################################
###########MAIN#PLAYBOOK#FOR#NOIA########
#########################################
##########INITIAL INSTALLATION###########
- hosts: new-hosts
  tasks:
    - name: Include Noia installation
      include_tasks:
        file: installation/noia.yml
        apply:
          tags:
            - install
    - name: Include Noia run node
      include_tasks:
        file: installation/noia.yml
        apply:
          tags:
            - run
    - include_role:
        name: uptime-monitor
  tags:
    - full-install

- hosts: new-hosts
  roles:
    - role: uptime-monitor
  tags:
    - metrics

- name: Include Dashboard generation
  import_playbook: monitoring/dashboard.yml
  tags:
    - dashboards

- name: Include prometheus configuration
  import_playbook: monitoring/prometheus_config.yml
  tags:
    - prometheus

##########SOFTWARE UPGRADE###########
- hosts: new-hosts
  tasks:
    - name: Include Noia installation
      include_tasks:
        file: installation/noia.yml
        apply:
          tags:
            - install
    - name: Include Noia run node
      include_tasks:
        file: installation/noia.yml
        apply:
          tags:
            - clean
    - name: Include Noia run node
      include_tasks:
        file: installation/noia.yml
        apply:
          tags:
            - update  
  tags:
    - upgrade


